# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  database: thinker_pro
  pool: 5
  username: root
  password: rubik
test:
  adapter: mysql2
  encoding: utf8
  database: thinker_test
  pool: 5
  username: root
  password: rubik
production:
  adapter: mysql2
  encoding: utf8
  database: thinker
  pool: 5
  username: root
  password: rubik
  
  